package cz.tefek.pluto.command.parser;

public enum EnumParserState
{
    BEGIN,
    READING_PREFIX,
    READING_COMMAND,
    READING_PARAMETER,
    READING_PARAMETER_QUOTED,
    READING_PARAMETER_CANDIDATE_UNQUOTE,
    READ_WHITESPACE,
    END_NO_PREFIX,
    END_NO_COMMAND,
    END_EMISSION_FAILURE,
    END,
    UNEXPECTED_STATE_FALLBACK;
}
