name: Gradle Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repository and all submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace --info -x test
